FROM docker.io/library/tomcat:9.0.102-jdk11

MAINTAINER "TEAM BETTOPIA<bettopia@gmail.com>"

RUN rm -rf /usr/local/tomcat/webapps/

EXPOSE 9090
ADD server.xml /usr/local/tomcat/conf/server.xml

ADD mysql-connector-java-8.0.28.jar /usr/local/tomcat/lib/
ADD target/game-game.war /usr/local/tomcat/webapps/BettingPoint.war
